### ISSUE TITLE
Voisko palvelin toimia nodella?

### ISSUE THREAD

**Issue by jakaarl** [web-selainohjelmointi/Elokuvakirjasto#4]
Eikö olisi kivaa, jos serverin pykäisi nodella ja sovelluksen build/deploy Herokussa hakisi npm- ja bower-riippuvuudet? Pientä ihmistä ahdistaa niiden pitäminen versionhallinnassa!

**Comment by jakaarl** [comment]
FYI, pitkät polut myöskin aiheuttavat ongelmia Windows-koneille. Tähän on kuitenkin workaround:
"git config core.longpaths true" (ks. https://github.com/msysgit/msysgit/wiki/Git-cannot-create-a-file-or-directory-with-a-long-path)

Ja tiedän, ei pitäisi käyttää Windowsia devaamiseen. Onhan se tuskallista. Mutta aina ei ole vaihtoehtoja.

**Comment by Kaltsoon** [comment]
Voisi ihan yhtä hyvin (tai paremminkin) toimia nodella, mutta jää toistaseksi itse toteutettavaksi. Siivoilen näitä vähän ennen seuraavan kurssin alkua. :)

**Comment by jakaarl** [comment]
Väsäsin nopean POCin ja tein pull requestin.
